/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eclipsesource_v8_V8Impl */

#ifndef _Included_com_eclipsesource_v8_V8Impl
#define _Included_com_eclipsesource_v8_V8Impl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _createIsolate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1createIsolate
  (JNIEnv *, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1release
  (JNIEnv *, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _contains
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8Impl__1contains
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getKeys
 * Signature: ()Ljava/util/Collection;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1getKeys
  (JNIEnv *, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getType
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8Impl__1getType
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getInteger
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8Impl__1getInteger
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getBoolean
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8Impl__1getBoolean
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getDouble
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8Impl__1getDouble
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8Impl__1getString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getArray
 * Signature: (Ljava/lang/String;)Lcom/eclipsesource/v8/V8Array;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1getArray
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _getObject
 * Signature: (Ljava/lang/String;)Lcom/eclipsesource/v8/V8Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1getObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _createParameterList
 * Signature: (I)Lcom/eclipsesource/v8/V8Array;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1createParameterList
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeIntFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8Impl__1executeIntFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeDoubleFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8Impl__1executeDoubleFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeStringFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8Impl__1executeStringFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeBooleanFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8Impl__1executeBooleanFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeArrayFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Lcom/eclipsesource/v8/V8Array;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1executeArrayFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeObjectFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Lcom/eclipsesource/v8/V8Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1executeObjectFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeVoidFunction
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1executeVoidFunction
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _add
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1add__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _add
 * Signature: (Ljava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1add__Ljava_lang_String_2Z
  (JNIEnv *, jobject, jstring, jboolean);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _add
 * Signature: (Ljava/lang/String;D)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1add__Ljava_lang_String_2D
  (JNIEnv *, jobject, jstring, jdouble);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _add
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1add__Ljava_lang_String_2Ljava_lang_String_2
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _addObject
 * Signature: (Ljava/lang/String;)Lcom/eclipsesource/v8/V8Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1addObject
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _addArray
 * Signature: (Ljava/lang/String;I)Lcom/eclipsesource/v8/V8Array;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1addArray
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _registerJavaMethod
 * Signature: (Ljava/lang/Object;Ljava/lang/String;[Ljava/lang/Class;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1registerJavaMethod
  (JNIEnv *, jobject, jobject, jstring, jobjectArray);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeIntScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)I
 */
JNIEXPORT jint JNICALL Java_com_eclipsesource_v8_V8Impl__1executeIntScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeDoubleScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)D
 */
JNIEXPORT jdouble JNICALL Java_com_eclipsesource_v8_V8Impl__1executeDoubleScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeStringScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eclipsesource_v8_V8Impl__1executeStringScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeBooleanScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_eclipsesource_v8_V8Impl__1executeBooleanScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeArrayScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Lcom/eclipsesource/v8/V8Array;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1executeArrayScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeObjectScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)Lcom/eclipsesource/v8/V8Object;
 */
JNIEXPORT jobject JNICALL Java_com_eclipsesource_v8_V8Impl__1executeObjectScript
  (JNIEnv *, jobject, jstring, jobject);

/*
 * Class:     com_eclipsesource_v8_V8Impl
 * Method:    _executeVoidScript
 * Signature: (Ljava/lang/String;Lcom/eclipsesource/v8/V8Array;)V
 */
JNIEXPORT void JNICALL Java_com_eclipsesource_v8_V8Impl__1executeVoidScript
  (JNIEnv *, jobject, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
