set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 17) # API level
#set(CMAKE_ANDROID_ARCH_ABI armeabi)
set(CMAKE_SYSTEM_PROCESSOR "armv7-a")
set(CMAKE_ANDROID_ARM_NEON 1)
set(CMAKE_ANDROID_NDK /build/android-ndk-r13b/)
set(CMAKE_ANDROID_STL_TYPE gnustl_static)
